name: FreedyMinigameMaker2
version: @version@
main: kr.jongwonlee.fmg.FMGPlugin
api-version: 1.13
authors: [ Bruce0203, Monday_blues_, Dixizer, andrewwindsor ]
description: Make arcade-games with script system
website: https://github.com/FreedyPlugins/FreedyMinigameMaker2
commands:
  fmg:
    description: minigame command
    usage: §c/fmg <join|left|create|delete|rl|item|loc|about> ...
permissions:
  freedyminigamemaker.admin:
    description: Permission to create, modify, or delete minigames
    default: op
  freedyminigamemaker.join.*:
    description: Permissions for command participation in minigames
    default: op
  freedyminigamemaker.quit.*:
    description: Permission to use the command to exit the mini-game
    default: op