on: push
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release ${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: jar/*.jar
          prerelease: false
